= Handling Errors in Javascript Functions
:description: Error handling in Javascript user-defined functions use the same standard exception mechanism as part of the language standard.
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

Errors that occur during the execution of an {sqlpp} statement are usually handled by the runtime, which will return a JSON object giving details of the error. 
For example, if we execute a record insertion function with a key that already exists:

[source, n1ql]
----
include::example$execute-airline-function-with-date.n1ql[]
----

then an error object is returned:

[source, json]
----
include::example$duplicate-key-error.json5[]
----

In most cases, it's a lot better if the Javascript function itself can handle errors that are likely to occur. 
This gives the developer the option of responding with a more user-friendly message, or taking an alternative course of action.

The following function will add an airline record, but will return an `failure` message if the attempt isn't successful.

[source, javascript]
----
include::example$add-airline-with-check-return.js[]
----

If the record key already exists, then calling this method with `EXECUTE FUNCTION`  will produce the following result:

[source, json]
----
include::example$add-airline-with-check-failure-return-response.jsonc[]
----

Alternatively, we can simply throw the error, rather than returning it as a string:

[source, javascript]
----
include::example$add-airline-with-check-throw.js[]
----

which will produce the following result:

[source,javascript]
----
include::example$add-airline-with-check-failure-throw-response.jsonc[]
----

As well as wrapping the expection in a detailed JSON object, there is another fundamental difference between throwing an error or returning it:

.Throw vs Return
****
Aside from the data returned, throwing an error or returning a value/error will affect how subsequent N1QL operations are processed.

*Returning an  error*:: If the JavaScript function _returns_ any value, then the N1QL runtime will assume that the function completed successfully, and the caller will continue to run subsequent statements.

*Throwing an error*::  If an error is _thrown_ then this is treated as an error condition, so further statements in the request will not be run.
****

You can, of course, throw the error object itself, rather than just a string.

[source, javascript]
----
include::example$add-airline-with-check-throw-object.js[]
----

which deliver a lot more useful information than just posting back a string:

[source, json]
----
include::example$add-airline-with-check-failure-throw-object-response.jsonc[]
----

Another approach is to parse the error using the `JSON.parse()` function and return the resulting object: 

[source, javascript]
----
include::example$add-airline-check-parse.js[]
----
<.> The `error` object contains a JSON string (`message`) detailing the nature of the error. 
It is much easier to interrogate the message if it's converted back into a JSON object on its own.
This code will send back the entire message structure.

[source, json]
----
include::example$parsed-error-in-full.json5[]
----

Once we know the structure of the error message, there's no reason why we can't carry out alternative actions depending on the type of error encountered:

[source, javascript]
----
include::example$add-airline-parse-check-2.js[]
----
<.> Check to see if this is a message that can be handled by the function itself.
<.> Strips out the `"Duplicate Key: "` part of the message, leaving just the duplicate key.

